"""empty message

Revision ID: 937927017dfc
Revises: 365cda344be8
Create Date: 2022-11-03 15:58:14.866470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937927017dfc'
down_revision = '365cda344be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
